<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Agents\TestAInspector.Agent.Contracts\TestAInspector.Agent.Contracts.csproj" />
    <ProjectReference Include="..\..\Analysis\TestAInspector.Analysis.Contracts\TestAInspector.Analysis.Contracts.csproj" />
    <ProjectReference Include="..\..\Parsing\TestAInspector.Parsing.Contracts\TestAInspector.Parsing.Contracts.csproj" />
    <ProjectReference Include="..\TestAInspector.Services.Contracts\TestAInspector.Services.Contracts.csproj" />
  </ItemGroup>

</Project>
