<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\TestAInspector.Common.Mvc\TestAInspector.Common.Mvc.csproj" />
    <ProjectReference Include="..\Core\Agents\TestAInspector.Agent.OpenAI\TestAInspector.Agent.OpenAI.csproj" />
    <ProjectReference Include="..\Core\Agents\TestAInspector.Agent.YandexGPT\TestAInspector.Agent.YandexGPT.csproj" />
    <ProjectReference Include="..\Core\Agents\TestAInspector.Agent\TestAInspector.Agent.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing.Archive\TestAInspector.Parsing.Archive.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing.Csv\TestAInspector.Parsing.Csv.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing.Json\TestAInspector.Parsing.Json.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing\TestAInspector.Parsing.csproj" />
    <ProjectReference Include="..\Core\Reporting\TestAInspector.Reporting\TestAInspector.Reporting.csproj" />
    <ProjectReference Include="..\Core\Services\TestAInspector.Services.Contracts\TestAInspector.Services.Contracts.csproj" />
    <ProjectReference Include="..\Core\Services\TestAInspector.Services\TestAInspector.Services.csproj" />
    <ProjectReference Include="..\Core\Validation\TestAInspector.Validation\TestAInspector.Validation.csproj" />
  </ItemGroup>

</Project>
