<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\TestAInspector.Common.Mvc\TestAInspector.Common.Mvc.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing.Csv\TestAInspector.Parsing.Csv.csproj" />
    <ProjectReference Include="..\Core\Parsing\TestAInspector.Parsing\TestAInspector.Parsing.csproj" />
    <ProjectReference Include="..\Core\Services\TestAInspector.Services.Contracts\TestAInspector.Services.Contracts.csproj" />
  </ItemGroup>

</Project>
