<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestAInspector.Parsing.Csv\TestAInspector.Parsing.Csv.csproj" />
    <ProjectReference Include="..\TestAInspector.Parsing.Json\TestAInspector.Parsing.Json.csproj" />
  </ItemGroup>

</Project>
