<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Analysis\TestAInspector.Analysis.Contracts\TestAInspector.Analysis.Contracts.csproj" />
    <ProjectReference Include="..\..\Reporting\TestAInspector.Reporting.Contracts\TestAInspector.Reporting.Contracts.csproj" />
    <ProjectReference Include="..\..\Validation\TestAInspector.Validation.Contracts\TestAInspector.Validation.Contracts.csproj" />
  </ItemGroup>

</Project>
